name: Profile summary cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: lestervillalon
          THEME: github_dark
          UTC_OFFSET: 8
